### PR TITLE
Create README based on old lemonade-stand README

### PR DESCRIPTION
**Pull request by davelab6**
:)

### CODE REVIEW

**Comment by signalwerk** [comment]
🤩 this is awesome! thank you for your effort! I just got fractions on twitter... what was exactly the intent of this repo. Like you wrote in the first line?
> "I want to design type full-time, how do I earn a living while making my work libre?"

**Comment by davelab6** [comment]
Yes, it's from the Twitter threads linked up from here

https://mobile.twitter.com/letterror/status/1046862295446503424

**Comment by chrissimpkins** [comment]
This looks great Dave.  Any idea about transitioning from CC0 (Lemonade Stand) to CC-by-SA (inc) for these documents?  Seems to be legit to do so from what I can gather from a read through of the Lemonade Stand CC0 public domain dedication.

**Comment by chrissimpkins** [comment]
Should this repo be focused on resources for how to earn money through libre typeface software development or should that be one (of several/many) focuses?  I am wondering if the project README is the proper location for this resource list or whether it should be on a document in the repository with a link from the README page.

@graphicore you had ideas about how this project develops.  Do you want to weigh in here or in an issue report thread so that we know how to deal with this PR?  

Feedback from others is definitely welcomed as well.  Weigh in if you have thoughts.

**Comment by graphicore** [comment]
> focused on resources for how to earn money through libre typeface software development or should that be one (of several/many) focuses

I'd tend to be open for more than just the "raw business models". The reason is, that we also need to implement these concepts in real live businesses and figure how to make them work etc. But there's more than one way to do things, so maybe that's also pointless at some level of detail.

This PR is good for me, we can reshape the repository when necessary.

**Comment by chrissimpkins** [comment]
This PR seems to be fodder for discussion around those topics and a resource in its own right.  Let's merge this to get the conversation started.

**Comment by pathumego** [comment]
>focused on resources for how to earn money through libre typeface software development or should that be one (of several/many) focuses

I  do not see this repo as a resource for people who want this information about how to make a living with libre fonts. I think we are ought to select or filter certain financing models in this PR with #2  based on the consensus on how it fits in with personal beliefs (Open-core, duel licensing and other ’semi-free‘ methods might not work for everybody) and personal requirements, scalability and viability in a live business as @graphicore pointed out. 

I am good to merge this now and re-structure later.

**Comment by chrissimpkins** [comment]
@pathumego please feel free to modify! do you see the goal here as the creation of some form of organization to carry this out or as a resource for those who wish to do so elsewhere?

**Comment by pathumego** [comment]
@chrissimpkins I was under the impression it is the former. But maybe `as a resource for those who wish to do so elsewhere` is a better approach given that SF already has its own goals. And as you outlined in your [ground rules post](https://github.com/orgs/source-foundry/teams/inc) `…If things grow in a way that makes a new organization account a more appropriate location for this project we can move it.`

Anyway my intention for participating here at this point is not to provide resources for someone else to setup something, but to discuss and find out how I can personally be a part of setting up that organisation that will facilitate scratching my itch of making libre fonts :) Any resources we compile are by-products in my view. However I am just super happy that we have this forum at the moment.

**Comment by chrissimpkins** [comment]
@pathumego I think that Lasse and Dave have the same vision as you do.  Look forward to the conversation too! Let's see where it leads.

**Comment by pathumego** [comment]
@chrissimpkins what is your vision?

**Comment by chrissimpkins** [comment]
@pathumego models for libre development based businesses/organizations have not been an area that I have ever explored. Discovery stage for me as these are all new concepts.  I will be able to contribute once I educate myself and chew on these issues a bit.  I can say that I would be interested in being part of an organization that helps libre type developers find a reliable revenue stream so that they can focus their time on what they do best and want to do rather than maintaining a second income generating job in the non-free realm or outside of software development altogether in order to make the ends meet.  I am intentionally using the term organization rather than business because this may be a non-profit foundation rather than a for-profit business model.  Remains to be seen.  Look forward to the conversation.

**Pull request merged**
